//
// CharacterGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CharacterGet200Response: Codable, JSONEncodable, Hashable {

    public var info: CharacterGet200ResponseInfo?
    public var results: [CharacterGet200ResponseResultsInner]?

    public init(info: CharacterGet200ResponseInfo? = nil, results: [CharacterGet200ResponseResultsInner]? = nil) {
        self.info = info
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case info
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(info, forKey: .info)
        try container.encodeIfPresent(results, forKey: .results)
    }
}

