//
// DefaultAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DefaultAPI {

    /**
     Получение списка команд
     
     - returns: [TeamsGet200ResponseInner]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func teamsGet() async throws -> [TeamsGet200ResponseInner] {
        return try await teamsGetWithRequestBuilder().execute().body
    }

    /**
     Получение списка команд
     - GET /teams
     - Возвращает список команд Dota 2, включая их идентификатор, рейтинг, количество побед и поражений.
     - returns: RequestBuilder<[TeamsGet200ResponseInner]> 
     */
    open class func teamsGetWithRequestBuilder() -> RequestBuilder<[TeamsGet200ResponseInner]> {
        let localVariablePath = "/teams"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[TeamsGet200ResponseInner]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
